name: Build Android v8a

on:
  push:
    branches: [ main ] # 或者是 master
    paths:
      - 'simple_live_core/**' # 核心修复逻辑变动
      - 'simple_live_app/**' # 版本号变动
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"

      # 1. 使用专用 Action 还原签名文件 (完美解决换行和编码损坏问题)
      - name: Restore Keystore
        id: keystore_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'my-release-key.jks'
          encodedString: ${{ secrets.ZI_FEI_YU }}

      # 2. 生成 key.properties
      - name: Create key.properties
        run: |
          cd simple_live_app/android
          # 使用 Action 输出的绝对路径，Gradle 能完美识别
          echo "storeFile=${{ steps.keystore_file.outputs.filePath }}" > key.properties
          echo "storePassword=123456" >> key.properties
          echo "keyPassword=123456" >> key.properties
          echo "keyAlias=mykey" >> key.properties
          
      - name: Clean and Restore packages
        run: |
          cd simple_live_app
          flutter clean
          # 强制删除插件注册缓存文件 (解决 auto_orientation_v2 幽灵报错)
          rm -f .flutter-plugins
          rm -f .flutter-plugins-dependencies
          rm -rf .dart_tool
          flutter pub get
          
      - name: Build APK
        run: |
          cd simple_live_app
          flutter clean
          flutter pub get
          # 针对 vivo/Android 15 优化
          flutter build apk --release --target-platform android-arm64 --no-tree-shake-icons
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SimpleLive-v8a-Build
          path: simple_live_app/build/app/outputs/flutter-apk/app-release.apk
